configuration: Release

os: Visual Studio 2015 CTP

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  - nuget restore src\Nine.Graphics.sln

build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true