configuration: Release
os: Visual Studio 2015 RC
environment:
  VisualStudioVersion: 14.0
  DNX_FEED: https://www.nuget.org/api/v2 
install:
  - dnvm install 1.0.0-beta4
  - dnu restore
test_script:
  - cmd: dnx test\Nine.Graphics.Test test
deploy:
- provider: NuGet
  api_key:
    secure: /Aez/maYDiX55BgGX9EkbhXBaBySsfdKifgB9SZxqySOrwtMVgPf7jOwS2XwKYJR
  on:
    branch: master